# Generated by Django 5.1.4 on 2025-01-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_ordereditem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Total_price',
            field=models.FloatField(default=0),
        ),
    ]
